---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/plex/support
    volumes:
      - ${SERVERS}/data/plex/plex:/plex
      - ${SERVERS}/data/plex/config:/config
      - ${SERVERS}/data/downloads:/downloads
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels: 
      tsdproxy.enable: true
      tsdproxy.tlsvalidate: false
      tsdproxy.container_port: "32400"
