---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/plex/support
    volumes:
      - ./plex:/plex
    ports:
      - 32400:32400
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels: 
      tsdproxy.enable: true
      tsdproxy.tlsvalidate: false
      tsdproxy.container_port: "32400"
